package vendingmachine.constant;

public enum VendingMachineStatus {
	INPUT_MONEY_IN_VENDING_MACHINE,
	SHOW_COINS_IN_VENDING_MACHINE,
	INPUT_GOODS_AND_PRICES_IN_VENDING_MACHINE,
	INPUT_USER_MONEY,
	SHOW_USER_LEFT_MONEY,
	INPUT_USER_GOODS,
	SHOW_LEFT_COIN
}
